simMeasure: ["intersec", "algnWoutOffs"]
nbSimSeqs: 100
simSeqLen: 10008
mutationRates: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
geneLen: 1000
nbCpys: 3
randSeqLen: 500
nbRandSeqs: 400