simMeasure: ["intersec", "algnWoutOffs"]
nbSimSeqs: 100
simSeqLen: 10000
minimap2DefaultK: 15
mutationRates: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
geneLen: 1000
nbCpys: 3
randSeqLen: 500
nbRandSeqs: 400
pbsimOutFlSufs: ["ref", "fastq", "maf"]
errorPatterns: ["23:31:46", "46:62:92", "92:124:184", "184:248:368", "368:496:736"]
globalSeed: 3096671072007954294
randomSampleSize: 1000
genomes: ["SAL_GB9998AA_AS", "humanChr20", "wheetChr1A-D"] #, "GCF_000001405.40_GRCh38.p14_genomic" 
bwaIdxFileSufs: ["amb", "ann", "bwt", "pac", "sa"]
prog: ["minimap2", "bwamem"]
scoringPatterns: ["c1_u1", "c1_u3", "c9_u1"]
implType: ["Py", "Cpp"]
divergenceRates: [0.01, 0.05]
substitutionIndelRates: [0.5, 1, 2]
copyNumber: 3
templLen: 50000
k: [9, 12, 15] #15 = default of minimap2 and Winnowmap2
PacBioPolymerase: "P6C4"
readCoverage: 2
readLength: 20000
matchScores: [1, 5, 10, 15, 30]
homologyThresholds: [0, -1000, -2000]
benchRepRuns: 5
readLens: [100, 250075, 500050, 750025, 1000000]
refRdRatio: 1.1
