name: Run make test

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake g++

      - name: Clone and install unordered_dense
        run: |
          git clone https://github.com/martinus/unordered_dense
          mkdir unordered_dense/build && cd unordered_dense/build
          cmake ..
          cmake --build . --target install
          cd ../.. # Go back to the root directory

      - name: Run make test
        run: make test
